<?php

namespace ContainerLSGg9GZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q6VWJexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q6VWJex' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q6VWJex'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'recette' => ['privates', '.errored..service_locator.q6VWJex.App\\Entity\\Recettes', NULL, 'Cannot autowire service ".service_locator.q6VWJex": it references class "App\\Entity\\Recettes" but no such service exists.'],
        ], [
            'manager' => '?',
            'recette' => 'App\\Entity\\Recettes',
        ]);
    }
}
