<?php

namespace ContainerLSGg9GZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ygyu5X5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ygyu5X5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ygyu5X5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'recette' => ['privates', '.errored..service_locator.Ygyu5X5.App\\Entity\\Recettes', NULL, 'Cannot autowire service ".service_locator.Ygyu5X5": it references class "App\\Entity\\Recettes" but no such service exists.'],
        ], [
            'recette' => 'App\\Entity\\Recettes',
        ]);
    }
}
