<?php

namespace ContainerLSGg9GZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.q6VWJex.App\Entity\Recettes' shared service.
     *
     * @return \App\Entity\Recettes
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.q6VWJex": it references class "App\\Entity\\Recettes" but no such service exists.');
    }
}
