<?php

namespace ContainerMpYwwTd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NkfRIhMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NkfRIhM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NkfRIhM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\RecettesController::delete' => ['privates', '.service_locator.Ygyu5X5', 'get_ServiceLocator_Ygyu5X5Service', true],
            'App\\Controller\\RecettesController::deleteImage' => ['privates', '.service_locator.XBdMERO', 'get_ServiceLocator_XBdMEROService', true],
            'App\\Controller\\RecettesController::edit' => ['privates', '.service_locator.Ygyu5X5', 'get_ServiceLocator_Ygyu5X5Service', true],
            'App\\Controller\\RecettesController::index' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RecettesController::randomRecipe' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RecettesController::show' => ['privates', '.service_locator.q6VWJex', 'get_ServiceLocator_Q6VWJexService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\RecettesController:delete' => ['privates', '.service_locator.Ygyu5X5', 'get_ServiceLocator_Ygyu5X5Service', true],
            'App\\Controller\\RecettesController:deleteImage' => ['privates', '.service_locator.XBdMERO', 'get_ServiceLocator_XBdMEROService', true],
            'App\\Controller\\RecettesController:edit' => ['privates', '.service_locator.Ygyu5X5', 'get_ServiceLocator_Ygyu5X5Service', true],
            'App\\Controller\\RecettesController:index' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RecettesController:randomRecipe' => ['privates', '.service_locator.Mg770zM', 'get_ServiceLocator_Mg770zMService', true],
            'App\\Controller\\RecettesController:show' => ['privates', '.service_locator.q6VWJex', 'get_ServiceLocator_Q6VWJexService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.Oi4_xhu', 'get_ServiceLocator_Oi4XhuService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\RecettesController::delete' => '?',
            'App\\Controller\\RecettesController::deleteImage' => '?',
            'App\\Controller\\RecettesController::edit' => '?',
            'App\\Controller\\RecettesController::index' => '?',
            'App\\Controller\\RecettesController::randomRecipe' => '?',
            'App\\Controller\\RecettesController::show' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\RecettesController:delete' => '?',
            'App\\Controller\\RecettesController:deleteImage' => '?',
            'App\\Controller\\RecettesController:edit' => '?',
            'App\\Controller\\RecettesController:index' => '?',
            'App\\Controller\\RecettesController:randomRecipe' => '?',
            'App\\Controller\\RecettesController:show' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
