<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE86TKhZ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE86TKhZ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerE86TKhZ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerE86TKhZ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerE86TKhZ\App_KernelProdContainer([
    'container.build_hash' => 'E86TKhZ',
    'container.build_id' => '955a6e73',
    'container.build_time' => 1616880034,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE86TKhZ');
