<?php

namespace ContainerE86TKhZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RecettesRepository' shared autowired service.
     *
     * @return \App\Repository\RecettesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RecettesRepository'] = new \App\Repository\RecettesRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
