<?php

namespace ContainerE86TKhZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecettesTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RecettesType' shared autowired service.
     *
     * @return \App\Form\RecettesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RecettesType'] = new \App\Form\RecettesType();
    }
}
