<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLSGg9GZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLSGg9GZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLSGg9GZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLSGg9GZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLSGg9GZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'LSGg9GZ',
    'container.build_id' => 'd71ffe4b',
    'container.build_time' => 1609778714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLSGg9GZ');
